spring:
  profiles:
    active: development,fast
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost/petitions?useUnicode=yes&characterEncoding=UTF-8
    username: petitions
    password: petitions
    driver-class-name: com.mysql.jdbc.Driver
  jpa.hibernate.ddl-auto: none
  #jpa:
    #show-sql: true

#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: DEBUG
server.error.whitelabel.enabled: false
security.basic.enabled: false

petitii:
  imap:
    server: imap.gmail.com
    port: 993
    ssl: true
    username: petitii.gov@gmail.com
    password: Q!W@E#R$T%Y^
    startDate: 06/12/2016
  emailAttachments:
    path: target/attachments
  petitionId:
    pattern: PET-%d-GOV

---
spring:
  profiles: development
flyway:
  locations: db/migration_prod,db/migration_dev

---
spring:
  profiles: production
flyway:
  locations: db/migration_dev